version: '3'
services:
  db:
    image: postgres:10.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: "bash -c 'python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000'"
    volumes:
      - .:/code
    ports:
      - 8080:8000
    depends_on:
      - db
volumes:
  postgres_data: